class endpoint {
    //path: registry path to the endpoint (string)
    //value: the value at the path that refers to the endpoint (string)
    //name: the name of the endpoint (string)
    //description: short description of the endpoint (string)
    //states: dictionary of all possible states of the endpoint; for delete endpoints, states should be "" for the deleted state and "0" for the existing state; for del_DWORD, states should be "" for the deleted state and the actual DWORD value(s) for the rest (dictionary)
    //section: specifies which section the endpoint should go in when it's not secured (string)
    //action: specifies whether the value needs to be just changed (add) or deleted in some way to make the endpoint work (delete) (string)
    //securekey: key value from the states dictionary that represents the endpoint's secure option (string)
    //defaultkey: key value from the states dictionary that represents the endpoint's default option (often it is the not configured state) (string)
    //del_DWORD: specifies if the endpoint is a delete endpoint or a del_DWORD endpoint if the action parameter is delete (default delete endpoint: the registry value swaps between being deleted and being a string value; del_DWORD endpoint: the registry value swaps between being deleted and being a DWORD value) (boolean)
    //version_added: the major windows version number in which the endpoint was added (lowest possible is the first version of windows 10) (integer)
    //version_removed: the major windows version number in which the endpoint was removed if any (integer/boolean)
    //dependencies: the specific states of other endpoints that the endpoint relies on to work (dictionary)
    constructor(path, value, name, description, states, section, action, securekey, defaultkey, del_DWORD, version_added, version_removed, dependencies) {
        this.name = name;
        this.registrypath = path;
        this.registryvalue = value;
        this.description = description;
        this.states = states;
        this.section = section;
        this.action = action;
        this.securekey = securekey;
        this.defaultkey = defaultkey;
        this.del_DWORD = del_DWORD;
        this.version_added = version_added;
        this.version_removed = version_removed;
        this.dependencies = dependencies;
    }
}
class category {
    //name: the name of the category (string)
    //description: short description of the category (string)
    //endpoints: list of endpoints in the category (list)
    constructor(name, description, endpoints) {
        this.name = name;
        this.description = description;
        this.endpoints = endpoints;
    }
    getSecurityStatus(regbyname) {
        let securedCount = 0;
        let totalCount = 0;
        this.endpoints.forEach(endpoint => {
            if (regbyname[endpoint.name]) {
                totalCount++;
                const registryEndpoint = regbyname[endpoint.name];
                if (registryEndpoint.state === registryEndpoint.securekey) {
                    securedCount++;
                }
            }
        });
        return {securedCount, totalCount, isFullySecured: securedCount === totalCount && totalCount > 0};
    }
    //return statistics about the endpoints in a category for display
}
window.AITEnable = new endpoint("HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\AppCompat", "AITEnable", "Application Telemetry", "Applications Can Send Anonymous Usage Data To Microsoft", {"": "Not Configured", "0": "Telemetry Disabled", "1": "Telemetry Enabled", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "insecure", "delete", "0", "", true, 10240, false, {"Customer Experience Improvement Program": ["", "1"]});
window.AllowCamera = new endpoint("HKLM:\\SOFTWARE\\Policies\\Microsoft\\Camera", "AllowCamera", "Camera Privacy", "Toggle Camera On Device", {"": "Not Configured", "0": "Force Disabled", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "optional", "delete", "0", "", true, 10240, false, {});
window.AllowClipboardHistory = new endpoint("HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\System", "AllowClipboardHistory", "Clipboard History", "Local Clipboard History Storage", {"0": "Clipboard History Disabled", "1": "Each User Can Decide", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "insecure", "add", "0", "1", false, 10240, false, {});
window.AllowCloudSearch = new endpoint("HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\Windows Search", "AllowCloudSearch", "Cloud Search", "Cortana And Windows Search Cloud-Based Account Access", {"": "Not Configured", "0": "Cloud Search Disabled", "1": "Cloud Search Enabled", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "insecure", "delete", "0", "", true, 10240, false, {});
window.AllowCortana = new endpoint("HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\Windows Search", "AllowCortana", "Allow Cortana", "Cortana Voice Assistant And Data Collection", {"": "Not Configured", "0": "Cortana Disabled", "1": "Cortana Enabled", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "insecure", "delete", "0", "", true, 10240, false, {});
window.AllowCrossDeviceClipboard = new endpoint("HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\System", "AllowCrossDeviceClipboard", "Cross-Device Clipboard", "Clipboard Synchronization Across Devices", {"": "Not Configured", "0": "Clipboard Sync Disabled", "1": "Clipboard Sync Allowed", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "insecure", "delete", "0", "", true, 10240, false, {});
window.AllowDeviceNameInTelemetry = new endpoint("HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\DataCollection", "AllowDeviceNameInTelemetry", "Device Name in Telemetry", "Device Name Can Be Sent To Microsoft In Diagnostic Data", {"": "Not Configured", "0": "Device Name Not Sent", "1": "Device Name Sent", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "insecure", "delete", "0", "", true, 17134, false, {"System Telemetry": ["", "1", "2", "3"]});
window.AllowFindMyDevice = new endpoint("HKLM:\\SOFTWARE\\Policies\\Microsoft\\FindMyDevice", "AllowFindMyDevice", "Find My Device", "Use of Location Data To Help With Device Tracking", {"": "Not Configured", "0": "Find My Device Disabled", "1": "Find My Device Enabled", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "optional", "delete", "0", "", true, 10240, false, {"Location Privacy": ["", "0"], "Location Access": ["0", "1"]});
window.AllowInputPersonalization = new endpoint("HKLM:\\SOFTWARE\\Policies\\Microsoft\\InputPersonalization", "AllowInputPersonalization", "Online Speech Recognition", "User Access to Microsoft Online Speech Recognition Services", {"0": "Speech Recognition Disabled", "1": "Each User Can Decide", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "optional", "add", "0", "1", false, 10240, false, {});
window.AllowLinguisticDataCollection = new endpoint("HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\TextInput", "AllowLinguisticDataCollection", "Inking And Typing Data", "Exfiltration Of Inking And Typing Analytics To Microsoft", {"0": "Sending Disabled", "1": "Each User Can Decide", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "insecure", "add", "0", "1", false, 17134, false, {"System Telemetry": ["", "3"]});
window.AllowNewsAndInterests = new endpoint("HKLM:\\SOFTWARE\\Policies\\Microsoft\\Dsh", "AllowNewsAndInterests", "Widgets", "Toggle Widgets", {"0": "Widgets Disabled", "1": "Each User Can Decide", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "insecure", "add", "0", "1", false, 10240, false, {});
window.AllowRemoteShellAccess = new endpoint("HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\WinRM\\Service\\WinRS", "AllowRemoteShellAccess", "Remote Shell", "Toggle Remote Shell", {"": "Not Configured", "0": "Force Disabled", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "insecure", "delete", "0", "", true, 10240, false, {});
window.AllowTelemetry = new endpoint("HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\DataCollection", "AllowTelemetry", "System Telemetry", "Diagnostic And Usage Data Collection", {"": "Not Configured", "0": "Security Only", "1": "Basic Telemetry", "2": "Enhanced Telemetry", "3": "Full Telemetry", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "insecure", "delete", "0", "", true, 10240, false, {});
window.BADFCCP = new endpoint("HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows Defender\\Windows Defender Exploit Guard\\ASR\\Rules", "7674ba52-37eb-4a4f-a9a1-f0f9a1619a2c", "Adobe Reader Child Processes", "Prevent Adobe From Being Exploited In Malware Campaigns", {"1": "Rule On", "0": "Rule Off", "2": "Rule Audit", "5": "Not Configured", "6": "Rule Warn", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "optional", "add", "1", "5", false, 16299, false, {"Windows Defender": ["0"], "Real-Time Monitoring": ["0"]});
window.BAOAFCCP = new endpoint("HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows Defender\\Windows Defender Exploit Guard\\ASR\\Rules", "d4f940ab-401b-4efc-aadc-ad5f3c50688a", "Office Application Child Processes", "Prevent Office Applications From Being Exploited In Malware Campaigns", {"1": "Rule On", "0": "Rule Off", "2": "Rule Audit", "5": "Not Configured", "6": "Rule Warn", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "optional", "add", "1", "5", false, 16299, false, {"Windows Defender": ["0"], "Real-Time Monitoring": ["0"]});
window.BAOVSD = new endpoint("HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows Defender\\Windows Defender Exploit Guard\\ASR\\Rules", "56a863a9-875e-4185-98a7-b882c64b5ce5", "Abuse Of Vulnerable Signed Drivers", "Prevent Vulnerable Signed Drivers From Gaining Kernel Access", {"1": "Rule On", "0": "Rule Off", "2": "Rule Audit", "5": "Not Configured", "6": "Rule Warn", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "optional", "add", "1", "5", false, 16299, false, {"Windows Defender": ["0"], "Real-Time Monitoring": ["0"]});
window.BCSFTWLSAS = new endpoint("HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows Defender\\Windows Defender Exploit Guard\\ASR\\Rules", "9e6c4e1f-7d60-472f-ba1a-a39ef669e4b2", "Credential Stealing From The LSASS", "Prevent Hacking Tools From Extracting LSASS Credentials", {"1": "Rule On", "0": "Rule Off", "2": "Rule Audit", "5": "Not Configured", "6": "Rule Warn", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "optional", "add", "1", "5", false, 16299, false, {"Windows Defender": ["0"], "Real-Time Monitoring": ["0"]});
window.BECFECAW = new endpoint("HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows Defender\\Windows Defender Exploit Guard\\ASR\\Rules", "be9ba2d9-53ea-4cdc-84e5-9b1eeee46550", "Executable Content From Email Clients", "Prevent Email Clients From Loading Executable Content", {"1": "Rule On", "0": "Rule Off", "2": "Rule Audit", "5": "Not Configured", "6": "Rule Warn", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "optional", "add", "1", "5", false, 16299, false, {"Windows Defender": ["0"], "Real-Time Monitoring": ["0"]});
window.BEOPOS = new endpoint("HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows Defender\\Windows Defender Exploit Guard\\ASR\\Rules", "5beb7efe-fd9a-4556-801d-275e5ffc04cc", "Potentially Obfuscated Scripts", "Prevent Execution of Files If Malicious Code Obfuscation Indicators Are Present", {"1": "Rule On", "0": "Rule Off", "2": "Rule Audit", "5": "Not Configured", "6": "Rule Warn", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "optional", "add", "1", "5", false, 16299, false, {"Windows Defender": ["0"], "Real-Time Monitoring": ["0"]});
window.BJOVFLDEC = new endpoint("HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows Defender\\Windows Defender Exploit Guard\\ASR\\Rules", "d3e037e1-3eb8-44c8-a917-57927947596d", "Malicious Web Scripts", "Prevent JavaScript Or VBScript From Launching Downloaded Executable Content", {"1": "Rule On", "0": "Rule Off", "2": "Rule Audit", "5": "Not Configured", "6": "Rule Warn", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "optional", "add", "1", "5", false, 16299, false, {"Windows Defender": ["0"], "Real-Time Monitoring": ["0"]});
window.BOAFCEC = new endpoint("HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows Defender\\Windows Defender Exploit Guard\\ASR\\Rules", "3b576869-a4ec-4529-8536-b80a7769e899", "Office Application Executable Content", "Prevent Office Applications From Being Used To Create Executable Content", {"1": "Rule On", "0": "Rule Off", "2": "Rule Audit", "5": "Not Configured", "6": "Rule Warn", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "optional", "add", "1", "5", false, 16299, false, {"Windows Defender": ["0"], "Real-Time Monitoring": ["0"]});
window.BOAFICIOP = new endpoint("HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows Defender\\Windows Defender Exploit Guard\\ASR\\Rules", "75668c1f-73b5-4cf0-bb93-3ecf5cb7cc84", "Office Application Code Injections", "Prevent Office Applications From Being Used To Inject Malicious Code Into External Processes", {"1": "Rule On", "0": "Rule Off", "2": "Rule Audit", "5": "Not Configured", "6": "Rule Warn", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "optional", "add", "1", "5", false, 16299, false, {"Windows Defender": ["0"], "Real-Time Monitoring": ["0"]});
window.BOCAFCCP = new endpoint("HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows Defender\\Windows Defender Exploit Guard\\ASR\\Rules", "26190899-1602-49e8-8b27-eb1d0a1ce869", "Office Communication Application Child Processes", "Prevent Outlook From Creating Malicious Child Processes", {"1": "Rule On", "0": "Rule Off", "2": "Rule Audit", "5": "Not Configured", "6": "Rule Warn", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "optional", "add", "1", "5", false, 16299, false, {"Windows Defender": ["0"], "Real-Time Monitoring": ["0"]});
window.BPCOFPAWC = new endpoint("HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows Defender\\Windows Defender Exploit Guard\\ASR\\Rules", "d1e49aac-8f56-4280-b9ba-993a6d77406c", "WMI And PSExec Process Creation", "Prevent Attackers From Using WMI and PSExec To Spawn Malicious Processes", {"1": "Rule On", "0": "Rule Off", "2": "Rule Audit", "5": "Not Configured", "6": "Rule Warn", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "optional", "add", "1", "5", false, 16299, false, {"Windows Defender": ["0"], "Real-Time Monitoring": ["0"]});
window.BPTWES = new endpoint("HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows Defender\\Windows Defender Exploit Guard\\ASR\\Rules", "e6db77e5-3df2-4cf1-b95a-636979351e5b", "WMI Malware Persistence", "Prevent Attackers From Using WMI For Fileless Command Execution", {"1": "Rule On", "0": "Rule Off", "2": "Rule Audit", "5": "Not Configured", "6": "Rule Warn", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "optional", "add", "1", "5", false, 16299, false, {"Windows Defender": ["0"], "Real-Time Monitoring": ["0"]});
window.BUAUPTRFU = new endpoint("HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows Defender\\Windows Defender Exploit Guard\\ASR\\Rules", "b2b3f03d-6a65-4f7b-a9c7-1c7ef74a9ba4", "Untrusted USB Processes", "Prevent Untrusted And Unsigned Processes From Running From USB", {"1": "Rule On", "0": "Rule Off", "2": "Rule Audit", "5": "Not Configured", "6": "Rule Warn", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "optional", "add", "1", "5", false, 16299, false, {"Windows Defender": ["0"], "Real-Time Monitoring": ["0"]});
window.BUOCOIST = new endpoint("HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows Defender\\Windows Defender Exploit Guard\\ASR\\Rules", "c0033c00-d16d-4114-a5a0-dc9b3a7d2ceb", "Impersonated System Tools", "Prevent Use Of Copied Or Impersonated System Tools", {"1": "Rule On", "0": "Rule Off", "2": "Rule Audit", "5": "Not Configured", "6": "Rule Warn", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "optional", "add", "1", "5", false, 16299, false, {"Windows Defender": ["0"], "Real-Time Monitoring": ["0"]});
window.BWACFOM = new endpoint("HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows Defender\\Windows Defender Exploit Guard\\ASR\\Rules", "92e97fa1-2edf-4476-bdd6-9dd0b4dddc7b", "API Calls From Office Macros", "Prevent Win32 API Calls From Office Macros (VBA)", {"1": "Rule On", "0": "Rule Off", "2": "Rule Audit", "5": "Not Configured", "6": "Rule Warn", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "optional", "add", "1", "5", false, 16299, false, {"Windows Defender": ["0"], "Real-Time Monitoring": ["0"]});
window.CEIPEnable = new endpoint("HKLM:\\SOFTWARE\\Policies\\Microsoft\\SQMClient\\Windows", "CEIPEnable", "Customer Experience Improvement Program", "Exfiltration Of Software And Hardware Usage Information To Microsoft", {"": "Not Configured", "0": "CEIP Disabled", "1": "CEIP Enabled", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "insecure", "delete", "0", "", true, 10240, false, {});
window.CSClipLevel = new endpoint("HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows NT\\Terminal Services", "CSClipLevel", "Remote Desktop Client-to-Server Clipboard", "Clipboard Redirection From Client To Server", {"": "Not Configured", "0": "No Restriction", "1": "Text Only", "2": "Disabled", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "optional", "delete", "2", "", true, 22000, false, {"Remote Desktop Clipboard Redirection": ["", "0"], "Remote Desktop Services": ["", "0"]});
window.DODownloadMode = new endpoint("HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\DeliveryOptimization", "DODownloadMode", "Delivery Optimization Mode", "Share Updates With Other Devices Using P2P", {"": "Not Configured", "0": "Disabled", "1": "LAN", "2": "Group", "3": "Internet", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "insecure", "delete", "0", "", true, 10240, false, {});
window.DisableADID = new endpoint("HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\AdvertisingInfo", "DisabledByGroupPolicy", "Advertising ID", "Advertising ID For Personalized Ads", {"0": "Each User Can Decide", "1": "Advertising ID Disabled", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "insecure", "add", "1", "0", false, 10240, false, {});
window.DisableAIDataAnalysis = new endpoint("HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\WindowsAI", "DisableAIDataAnalysis", "Disable Windows Recall", "AI Snapshots And Data Analysis", {"": "Not Configured", "0": "Recall Snapshots Allowed", "1": "Recall Snapshots Disabled", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "insecure", "delete", "1", "", true, 26100, false, {});
window.DisableAccountNotifications = new endpoint("HKCU:\\SOFTWARE\\Policies\\Microsoft\\Windows\\CurrentVersion\\AccountNotifications", "DisableAccountNotifications", "Account Notifications", "Invasive Microsoft Account Pop-ups", {"": "Not Configured", "0": "Notifications Enabled", "1": "Notifications Disabled", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "optional", "delete", "1", "", true, 19041, false, {});
window.DisableAntiSpyware = new endpoint("HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows Defender", "DisableAntiSpyware", "Windows Defender", "Toggle Windows Defender (Remove Other Anti-Viruses Before Force Enabling)", {"": "Not Configured", "0": "Force Enabled", "1": "Force Disabled", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "optional", "delete", "0", "", true, 10240, false, {});
window.DisableApplicationFootprint = new endpoint("HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\AppCompat", "DisableApplicationFootprint", "Application Footprint Collection", "Collection Of Application Behavior And Usage Patterns", {"": "Not Configured", "0": "Footprint Collection Enabled", "1": "Footprint Collection Disabled", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "insecure", "delete", "1", "", true, 26100, false, {});
window.DisableBlockAtFirstSeen = new endpoint("HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows Defender\\Spynet", "DisableBlockAtFirstSeen", "Block New Malware Using Cloud Insights", "Use Of MAPS To Detect And Act On New Malware Quickly", {"": "Not Configured", "0": "Block At First Sight Enabled", "1": "Block At First Sight Disabled", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "optional", "delete", "0", "", true, 10240, false, {"Windows Defender": ["0"], "Real-Time Monitoring": ["0"], "Defender MAPS Reporting": ["1", "2"], "Malicious File Sample Submission": ["0", "1", "3"], "Scan All Downloads And Attachments": ["0"]});
window.DisableFileHistory = new endpoint("HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\FileHistory", "Disabled", "File History", "Record Keeping Of File Versions Through Time", {"": "Each User Can Decide", "1": "Disable File History", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "optional", "delete", "1", "", true, 10240, false, {});
window.DisableFileSyncNGSC = new endpoint("HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\OneDrive", "DisableFileSyncNGSC", "OneDrive Sync", "OneDrive File Storage And Sync", {"": "Not Configured", "0": "OneDrive Sync Allowed", "1": "OneDrive Sync Disabled", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "optional", "delete", "1", "", true, 10240, false, {});
window.DisableGraphRecentItems = new endpoint("HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\Explorer", "DisableGraphRecentItems", "Cloud File Insights", "File Explorer Account-Based Insights And Recommendations", {"": "Not Configured", "0": "Cloud Insights Enabled", "1": "Cloud Insights Disabled", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "insecure", "delete", "1", "", true, 22000, false, {});
window.DisableIOAVProtection = new endpoint("HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows Defender\\Real-Time Protection", "DisableIOAVProtection", "Scan All Downloads And Attachments", "Malware Scanning Of Downloaded Internet Files", {"": "Not Configured", "0": "Force Enabled", "1": "Force Disabled", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "optional", "delete", "0", "", true, 10240, false, {"Windows Defender": ["0"], "Real-Time Monitoring": ["0"]});
window.DisableInstallTracing = new endpoint("HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\AppCompat", "DisableInstallTracing", "Installation Tracking", "Windows Application Installation Tracking", {"": "Not Configured", "0": "Install Tracking Enabled", "1": "Install Tracking Disabled", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "insecure", "delete", "1", "", true, 26100, false, {});
window.DisableInventory = new endpoint("HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\AppCompat", "DisableInventory", "Inventory Collector", "Windows Inventory Of Applications, Files, Devices, And Drivers", {"": "Inventory Enabled", "1": "Inventory Disabled", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "insecure", "delete", "1", "", true, 10240, false, {"Customer Experience Improvement Program": ["", "1"]});
window.DisableLocation = new endpoint("HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\LocationAndSensors", "DisableLocation", "Location Privacy", "Toggle Location On Device", {"": "Not Configured", "0": "Location Enabled", "1": "Location Disabled", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "optional", "delete", "1", "", true, 10240, false, {});
window.DisableLocationScripting = new endpoint("HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\LocationAndSensors", "DisableLocationScripting", "Location Scripting", "Toggle Alternate Location Tracking On Device", {"": "Not Configured", "0": "Location Scripting Enabled", "1": "Location Scripting Disabled", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "optional", "delete", "1", "", true, 10240, false, {});
window.DisablePeerNetworking = new endpoint("HKLM:\\SOFTWARE\\Policies\\Microsoft\\Peernet", "Disabled", "Peer Networking", "Microsoft Peer-to-Peer Networking Services", {"": "P2P Networking Allowed", "1": "P2P Networking Disabled", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "insecure", "delete", "1", "", true, 10240, false, {});
window.DisableRealTimeMonitoring = new endpoint("HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows Defender\\Real-Time Protection", "DisableRealTimeMonitoring", "Real-Time Monitoring", "Real-Time Detection Of Malware By Windows Defender", {"": "Not Configured", "0": "Force Enabled", "1": "Force Disabled", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "optional", "delete", "0", "", true, 10240, false, {"Windows Defender": ["0"]});
window.DisableSearchBoxSuggestions = new endpoint("HKCU:\\SOFTWARE\\Policies\\Microsoft\\Windows\\Explorer", "DisableSearchBoxSuggestions", "Windows Search Web Access", "Web Search Results In Windows Search", {"": "Web Results Enabled", "1": "Web Results Disabled" , "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "insecure", "delete", "1", "", true, 19041, false, {});
window.DisableSensors = new endpoint("HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\LocationAndSensors", "DisableSensors", "Toggle Sensors", "Toggle All Device Sensors For Privacy", {"": "Not Configured", "0": "Sensors Enabled", "1": "Sensors Disabled", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "insecure", "delete", "1", "", true, 10240, false, {});
window.DisableSettingSync = new endpoint("HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\SettingSync", "DisableSettingSync", "Toggle Sync", "Toggle The Ability Of Windows To Sync Data To The Cloud", {"0": "Each User Can Decide", "2": "No Sync", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "optional", "add", "2", "0", false, 10240, false, {});
window.DisableSoftLanding = new endpoint("HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\CloudContent", "DisableSoftLanding", "Windows Tips", "Toggle Windows Tips And Suggestions", {"": "Not Configured", "0": "Tips Allowed", "1": "Tips Disabled", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "insecure", "delete", "1", "", true, 10240, false, {});
window.DisableTailoredExperiencesWithDiagnosticData = new endpoint("HKCU:\\SOFTWARE\\Policies\\Microsoft\\Windows\\CloudContent", "DisableTailoredExperiencesWithDiagnosticData", "Tailored Experiences", "Windows Usage Of Diagnostic Data For Personalized Experiences", {"0": "Current User Can Decide", "1": "Tailored Experiences Disabled", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "insecure", "add", "1", "0", false, 15063, false, {});
window.DisableUAR = new endpoint("HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\AppCompat", "DisableUAR", "Steps Recorder", "Keeps A Record Of Steps Taken By The User For Error Reporting", {"": "Not Configured", "0": "Steps Recorder Enabled", "1": "Steps Recorder Disabled", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "insecure", "delete", "1", "", true, 10240, false, {});
window.DisableWindowsConsumerFeatures = new endpoint("HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\CloudContent", "DisableWindowsConsumerFeatures", "Microsoft Consumer Experiences", "Personalized Recommendations From Microsoft", {"": "Not Configured", "0": "Consumer Features Allowed", "1": "Consumer Features Disabled", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "insecure", "delete", "1", "", true, 10240, false, {});
window.DisableWindowsErrorReporting = new endpoint("HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\Windows Error Reporting", "Disabled", "Windows Error Reporting", "Sending Error Reports To Microsoft", {"": "Not Configured", "0": "Error Reporting Allowed", "1": "Error Reporting Disabled", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "optional", "delete", "1", "", true, 10240, false, {});
window.DisableWindowsSpotlightFeatures = new endpoint("HKCU:\\SOFTWARE\\Policies\\Microsoft\\Windows\\CloudContent", "DisableWindowsSpotlightFeatures", "Windows Spotlight", "Spotlight Backgrounds, Windows Tips, Windows Consumer Features, And Related Services", {"": "Not Configured", "0": "Spotlight Allowed", "1": "Spotlight Disabled", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "insecure", "delete", "1", "", true, 10240, false, {});
window.EnableActivityFeed = new endpoint("HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\System", "EnableActivityFeed", "Activity Feed", "Windows Timeline And Activity Tracking", {"": "Not Configured", "0": "Activity Feed Disabled", "1": "Activity Feed Enabled", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "insecure", "delete", "0", "", true, 10240, false, {});
window.EnableCdp = new endpoint("HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\System", "EnableCdp", "Shared Experiences", "Cross-Device Data Sharing", {"0": "Continue Experiences Disabled", "1": "Each User Can Decide", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "optional", "add", "0", "1", false, 10240, false, {});
window.EnableNetworkProtection = new endpoint("HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows Defender\\Windows Defender Exploit Guard\\Network Protection", "EnableNetworkProtection", "Advanced Web Protection", "Blocking Of Malicious Sites And Phishing Sites", {"": "Not Configured", "1": "On", "0": "Off", "2": "Audit", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "optional", "delete", "1", "", true, 16299, false, {"Windows Defender": ["0"], "Real-Time Monitoring": ["0"]});
window.EnableScriptBlockLogging = new endpoint("HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\PowerShell\\ScriptBlockLogging", "EnableScriptBlockLogging", "PowerShell Logging", "PowerShell Command Recording In Event Log", {"": "Not Configured", "0": "Logging Disabled", "1": "Logging Enabled", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "optional", "delete", "1", "", true, 10240, false, {});
window.fDenyTSConnections = new endpoint("HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows NT\\Terminal Services", "fDenyTSConnections", "Remote Desktop Services", "Toggle Remote Desktop Services", {"": "Not Configured", "0": "Remote Desktop Services Enabled", "1": "Remote Desktop Services Disabled", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "optional", "delete", "1", "", true, 10240, false, {});
window.fDisableAudioCapture = new endpoint("HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows NT\\Terminal Services", "fDisableAudioCapture", "Remote Desktop Audio Recording", "Audio Recording In Remote Desktop Session", {"": "Not Configured", "0": "Audio Recording Allowed", "1": "Audio Recording Disabled", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "optional", "delete", "1", "", true, 10240, false, {"Remote Desktop Services": ["", "0"]});
window.fDisableCdm = new endpoint("HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows NT\\Terminal Services", "fDisableCdm", "Remote Desktop Drive Redirection", "Drive Sharing In Remote Desktop Session", {"": "Not Configured", "0": "Drive Sharing Allowed", "1": "Drive Sharing Disabled", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "optional", "delete", "1", "", true, 10240, false, {"Remote Desktop Services": ["", "0"]});
window.fDisableClip = new endpoint("HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows NT\\Terminal Services", "fDisableClip", "Remote Desktop Clipboard Redirection", "Clipboard Redirection In Remote Desktop Session", {"": "Not Configured", "0": "Clipboard Sharing Allowed", "1": "Clipboard Sharing Disabled", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "optional", "delete", "1", "", true, 10240, false, {"Remote Desktop Services": ["", "0"]});
window.fDisableLocationRedir = new endpoint("HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows NT\\Terminal Services", "fDisableLocationRedir", "Remote Desktop Location Redirection", "Location Sharing In Remote Desktop Session", {"": "Not Configured", "0": "Location Sharing Allowed", "1": "Location Sharing Disabled", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "optional", "delete", "1", "0", true, 19043, false, {"Remote Desktop Services": ["", "0"]});
window.LetAppsAccessAccountInfo = new endpoint("HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\AppPrivacy", "LetAppsAccessAccountInfo", "Account Info Access", "Installed Apps Can Access Your Account Info", {"0": "Each User Can Decide", "1": "Apps Are Allowed", "2": "Apps Are Not Allowed", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "optional", "add", "2", "0", false, 10240, false, {});
window.LetAppsAccessBackgroundSpatialPerception = new endpoint("HKLM:\\Software\\Policies\\Microsoft\\Windows\\AppPrivacy", "LetAppsAccessBackgroundSpatialPerception", "Background Movement Access", "Installed Apps Can Track User Head/Hand Movements While Running In The Background", {"0": "Each User Can Decide", "1": "Apps Are Allowed", "2": "Apps Are Not Allowed", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "optional", "add", "2", "0", false, 10240, false, {});
window.LetAppsAccessCalendar = new endpoint("HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\AppPrivacy", "LetAppsAccessCalendar", "Calendar Access", "Installed Apps Can Access Your Calendar", {"0": "Each User Can Decide", "1": "Apps Are Allowed", "2": "Apps Are Not Allowed", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "optional", "add", "2", "0", false, 10240, false, {});
window.LetAppsAccessCallHistory = new endpoint("HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\AppPrivacy", "LetAppsAccessCallHistory", "Call History Access", "Installed Apps Can Access Your Call History", {"0": "Each User Can Decide", "1": "Apps Are Allowed", "2": "Apps Are Not Allowed", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "optional", "add", "2", "0", false, 10240, false, {});
window.LetAppsAccessCamera = new endpoint("HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\AppPrivacy", "LetAppsAccessCamera", "Camera Access", "Installed Apps Can Access Your Camera", {"0": "Each User Can Decide", "1": "Apps Are Allowed", "2": "Apps Are Not Allowed", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "optional", "add", "2", "0", false, 10240, false, {"Camera Privacy": [""]});
window.LetAppsAccessContacts = new endpoint("HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\AppPrivacy", "LetAppsAccessContacts", "Contacts Access", "Installed Apps Can Access Your Contacts", {"0": "Each User Can Decide", "1": "Apps Are Allowed", "2": "Apps Are Not Allowed", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "optional", "add", "2", "0", false, 10240, false, {});
window.LetAppsAccessEmail = new endpoint("HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\AppPrivacy", "LetAppsAccessEmail", "Email Access", "Installed Apps Can Access And Send Emails", {"0": "Each User Can Decide", "1": "Apps Are Allowed", "2": "Apps Are Not Allowed", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "optional", "add", "2", "0", false, 10240, false, {});
window.LetAppsAccessGazeInput = new endpoint("HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\AppPrivacy", "LetAppsAccessGazeInput", "Eye Tracking Access", "Installed Apps Can Access Eye Tracking Data From Gaze Input Devices", {"0": "Each User Can Decide", "1": "Apps Are Allowed", "2": "Apps Are Not Allowed", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "optional", "add", "2", "0", false, 10240, false, {});
window.LetAppsAccessGraphicsCaptureProgrammatic = new endpoint("HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\AppPrivacy", "LetAppsAccessGraphicsCaptureProgrammatic", "Screenshot Capture Access", "Installed Apps Can Take Screenshots Of Windows And Displays", {"0": "Each User Can Decide", "1": "Apps Are Allowed", "2": "Apps Are Not Allowed", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "optional", "add", "2", "0", false, 10240, false, {});
window.LetAppsAccessGraphicsCaptureWithoutBorder = new endpoint("HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\AppPrivacy", "LetAppsAccessGraphicsCaptureWithoutBorder", "Borderless Screenshot Capture Acess", "Installed Apps Can Take Borderless Screenshots of Windows and Displays", {"0": "Each User Can Decide", "1": "Apps Are Allowed", "2": "Apps Are Not Allowed", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "optional", "add", "2", "0", false, 10240, false, {});
window.LetAppsAccessHumanPresence = new endpoint("HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\AppPrivacy", "LetAppsAccessHumanPresence", "Presence Sensing Access", "Installed Apps Can Access Presence Sensing Information", {"0": "Each User Can Decide", "1": "Apps Are Allowed", "2": "Apps Are Not Allowed", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "optional", "add", "2", "0", false, 10240, false, {});
window.LetAppsAccessLocation = new endpoint("HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\AppPrivacy", "LetAppsAccessLocation", "Location Access", "Installed Apps Can Access Your Location Data", {"0": "Each User Can Decide", "1": "Apps Are Allowed", "2": "Apps Are Not Allowed", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "optional", "add", "2", "0", false, 10240, false, {"Location Privacy": ["", "0"]});
window.LetAppsAccessMessaging = new endpoint("HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\AppPrivacy", "LetAppsAccessMessaging", "Messaging Access", "Installed Apps Can Access Your Messages (SMS/MMS)", {"0": "Each User Can Decide", "1": "Apps Are Allowed", "2": "Apps Are Not Allowed", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "optional", "add", "2", "0", false, 10240, false, {});
window.LetAppsAccessMicrophone = new endpoint("HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\AppPrivacy", "LetAppsAccessMicrophone", "Microphone Access", "Installed Apps Can Access Your Microphone", {"0": "Each User Can Decide", "1": "Apps Are Allowed", "2": "Apps Are Not Allowed", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "optional", "add", "2", "0", false, 10240, false, {});
window.LetAppsAccessMotion = new endpoint("HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\AppPrivacy", "LetAppsAccessMotion", "Motion Data Access", "Installed Apps Can Access Motion And Movement Data From Sensors", {"0": "Each User Can Decide", "1": "Apps Are Allowed", "2": "Apps Are Not Allowed", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "optional", "add", "2", "0", false, 10240, false, {});
window.LetAppsAccessNotifications = new endpoint("HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\AppPrivacy", "LetAppsAccessNotifications", "Notification Access", "Installed Apps Can Access Your Notifications From Other Apps", {"0": "Each User Can Decide", "1": "Apps Are Allowed", "2": "Apps Are Not Allowed", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "optional", "add", "2", "0", false, 10240, false, {});
window.LetAppsAccessPhone = new endpoint("HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\AppPrivacy", "LetAppsAccessPhone", "Phone Access", "Installed Apps Can Make Phone Calls Using Your Device", {"0": "Each User Can Decide", "1": "Apps Are Allowed", "2": "Apps Are Not Allowed", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "optional", "add", "2", "0", false, 10240, false, {});
window.LetAppsAccessRadios = new endpoint("HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\AppPrivacy", "LetAppsAccessRadios", "Radio Access", "Installed Apps Can Control WiFi, Bluetooth, And Other Radios", {"0": "Each User Can Decide", "1": "Apps Are Allowed", "2": "Apps Are Not Allowed", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "optional", "add", "2", "0", false, 10240, false, {});
window.LetAppsAccessTasks = new endpoint("HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\AppPrivacy", "LetAppsAccessTasks", "Tasks Access", "Installed Apps Can Access Task Information", {"0": "Each User Can Decide", "1": "Apps Are Allowed", "2": "Apps Are Not Allowed", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "optional", "add", "2", "0", false, 10240, false, {});
window.LetAppsAccessTrustedDevices = new endpoint("HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\AppPrivacy", "LetAppsAccessTrustedDevices", "Trusted Device Access", "Installed Apps Can Access Trusted Devices", {"0": "Each User Can Decide", "1": "Apps Are Allowed", "2": "Apps Are Not Allowed", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "optional", "add", "2", "0", false, 10240, false, {});
window.LetAppsActivateWithVoice = new endpoint("HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\AppPrivacy", "LetAppsActivateWithVoice", "Voice Activation", "Installed Apps Can Be Activated With Voice Commands", {"0": "Each User Can Decide", "1": "Apps Are Allowed", "2": "Apps Are Not Allowed", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "optional", "add", "2", "0", false, 10240, false, {});
window.LetAppsActivateWithVoiceAboveLock = new endpoint("HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\AppPrivacy", "LetAppsActivateWithVoiceAboveLock", "Voice Activation Above Lock", "Installed Apps Can Be Activated With Voice While System Is Locked", {"0": "Each User Can Decide", "1": "Apps Are Allowed", "2": "Apps Are Not Allowed", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "optional", "add", "2", "0", false, 10240, false, {});
window.LetAppsGetDiagnosticInfo = new endpoint("HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\AppPrivacy", "LetAppsGetDiagnosticInfo", "Diagnostic Data Access", "Installed Apps Can Access Diagnostic Information About Other Apps", {"0": "Each User Can Decide", "1": "Apps Are Allowed", "2": "Apps Are Not Allowed", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "optional", "add", "2", "0", false, 15063, false, {});
window.LetAppsRunInBackground = new endpoint("HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\AppPrivacy", "LetAppsRunInBackground", "Background App Activity", "Installed Apps Can Run In Background", {"0": "Each User Can Decide", "1": "Apps Are Allowed", "2": "Apps Are Not Allowed", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "optional", "add", "2", "0", false, 10240, false, {});
window.LetAppsSyncWithDevices = new endpoint("HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\AppPrivacy", "LetAppsSyncWithDevices", "Device Sync Access", "Installed Apps Can Communicate With Unpaired Wireless Devices", {"0": "Each User Can Decide", "1": "Apps Are Allowed", "2": "Apps Are Not Allowed", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "optional", "add", "2", "0", false, 10240, false, {});
window.MSAOptional = new endpoint("HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System", "MSAOptional", "Microsoft Account Requirement", "Microsoft Account Requirement For Store Apps", {"": "Not Configured", "0": "Microsoft Account Required", "1": "Microsoft Account Optional", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "optional", "delete", "1", "", true, 10240, false, {});
window.MessageCloudSync = new endpoint("HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\Messaging", "AllowMessageSync", "Message Cloud Sync", "Synchronization Of Text Messages To Microsoft Cloud", {"0": "Message Sync Disabled", "1": "Each User Can Decide", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "optional", "add", "0", "1", false, 16299, false, {});
window.MpCloudBlockLevel = new endpoint("HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows Defender\\MpEngine", "MpCloudBlockLevel", "Defender Protection Level", "Aggressiveness Of Windows Defender", {"": "Not Configured", "0": "Default", "1": "Moderate", "2": "High", "4": "High+", "6": "Zero Tolerance", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "optional", "delete", "6", "", true, 10240, false, {"Windows Defender": ["0"], "Real-Time Monitoring": ["0"]});
window.NeverShowExt = new endpoint("HKLM:\\SOFTWARE\\Classes\\lnkfile", "NeverShowExt", ".lnk Extension Visibility", ".lnk Disguised Malicious File Visibility", {"": "Extensions Shown", "0": "Extensions Hidden", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "optional", "delete", "", "0", false, 10240, false, {});
window.NoDriveTypeAutoRun = new endpoint("HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\Explorer", "NoDriveTypeAutoRun", "Toggle AutoPlay/AutoRun Feature", "Automatic Execution Of Content From Removable Media", {"": "AutoPlay/AutoRun Enabled", "255": "AutoPlay/AutoRun Disabled", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "insecure", "delete", "255", "", true, 10240, false, {});
window.NoRun = new endpoint("HKCU:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\Explorer", "NoRun", "Run Dialog", "Social Engineering Run Dialog (Win+R) Attacks", {"": "Not Configured", "0": "Run Enabled", "1": "Run Disabled", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "optional", "delete", "1", "", true, 10240, false, {});
window.PUAProtection = new endpoint("HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows Defender", "PUAProtection", "PUA Detection", "Potentially Unwanted Application Detection", {"": "Each User Can Decide", "0": "PUAs Allowed", "1": "PUAs Blocked", "2": "Audit Mode", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "optional", "delete", "1", "", true, 14393, false, {"Windows Defender": ["0"], "Real-Time Monitoring": ["0"]});
window.PreventDeviceMetadataFromNetwork = new endpoint("HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\Device Metadata", "PreventDeviceMetadataFromNetwork", "Automatic Driver Software Installation", "3rd-Party Elevated Driver Utility Software Automatic Installations", {"0": "Each Driver Can Be Configured", "1": "Installations Not Allowed", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "optional", "add", "1", "0", false, 10240, false, {});
window.PreventNetworkTrafficPreUserSignIn = new endpoint("HKLM:\\SOFTWARE\\Microsoft\\OneDrive", "PreventNetworkTrafficPreUserSignIn", "Unsolicited OneDrive Traffic", "OneDrive Network Traffic Generation Before Use", {"": "Not Configured", "0": "Traffic Enabled", "1": "Traffic Disabled", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "insecure", "delete", "1", "", true, 10240, false, {});
window.PublishUserActivities = new endpoint("HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\System", "PublishUserActivities", "Saving User Activities", "User Activity History On This Device", {"0": "Saving Disabled", "1": "Each User Can Decide", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "insecure", "add", "0", "1", false, 10240, false, {});
window.SCClipLevel = new endpoint("HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows NT\\Terminal Services", "SCClipLevel", "Remote Desktop Server-to-Client Clipboard", "Clipboard Redirection From Server To Client", {"": "Not Configured", "0": "No Restriction", "1": "Text Only", "2": "Disabled", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "optional", "delete", "2", "", true, 22000, false, {"Remote Desktop Clipboard Redirection": ["", "0"], "Remote Desktop Services": ["", "0"]});
window.ScenarioExecutionEnabled = new endpoint("HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\WDI", "ScenarioExecutionEnabled", "Diagnostic Policy Service", "Toggle Troubleshooting Diagnostics", {"": "Not Configured", "0": "Troubleshooting Disabled", "1": "Troubleshooting Enabled", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "insecure", "delete", "0", "", true, 10240, false, {});
window.SpynetReporting = new endpoint("HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows Defender\\Spynet", "SpynetReporting", "Defender MAPS Reporting", "Microsoft Active Protection Service", {"": "Not Configured", "0": "MAPS Disabled", "1": "Basic Membership", "2": "Advanced Membership", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "optional", "delete", "1", "", true, 10240, false, {"Windows Defender": ["0"], "Real-Time Monitoring": ["0"]});
window.SubmitSamplesConsent = new endpoint("HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows Defender\\Spynet", "SubmitSamplesConsent", "Malicious File Sample Submission", "Possibly Malicious File Submission To Microsoft For Further Analysis", {"": "Not Configured", "0": "Always Prompt Before Submission", "1": "Send Safe Samples Automatically", "2": "Never Send Samples", "3": "Send All Samples Automatically", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "optional", "delete", "0", "", true, 10240, false, {"Windows Defender": ["0"], "Real-Time Monitoring": ["0"], "Defender MAPS Reporting": ["1", "2"]});
window.TurnOffWindowsCopilot = new endpoint("HKCU:\\SOFTWARE\\Policies\\Microsoft\\Windows\\WindowsCopilot", "TurnOffWindowsCopilot", "Copilot", "Toggle Copilot", {"": "Not Configured", "0": "Copilot Allowed", "1": "Copilot Force Disabled", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "optional", "delete", "1", "", true, 19041, false, {});
window.UAPAR = new endpoint("HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows Defender\\Windows Defender Exploit Guard\\ASR\\Rules", "c1db55ab-c21a-4637-bb3f-a12568109d35", "Ransomware Protection", "Advanced Protection Against Ransomware", {"1": "Rule On", "0": "Rule Off", "2": "Rule Audit", "5": "Not Configured", "6": "Rule Warn", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "optional", "add", "1", "5", false, 16299, false, {"Windows Defender": ["0"], "Real-Time Monitoring": ["0"]});
window.UploadUserActivities = new endpoint("HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\System", "UploadUserActivities", "Upload User Activities", "Uploading Of Locally Saved User Data", {"0": "Upload Disabled", "1": "Each User Can Decide", "Corrupted": "An Error Occured When Looking Up This Endpoint"}, "insecure", "add", "0", "1", false, 10240, false, {});

window.categories = [
    new category(
        "App Privacy",
        "Endpoints That Control What Device Features And Data Apps Can Access",
        [window.LetAppsAccessAccountInfo, window.LetAppsAccessBackgroundSpatialPerception, window.LetAppsAccessCalendar, 
        window.LetAppsAccessCallHistory, window.LetAppsAccessCamera, window.LetAppsAccessContacts, 
        window.LetAppsAccessEmail, window.LetAppsAccessGazeInput, window.LetAppsAccessGraphicsCaptureProgrammatic, 
        window.LetAppsAccessGraphicsCaptureWithoutBorder, window.LetAppsAccessHumanPresence, window.LetAppsAccessLocation, 
        window.LetAppsAccessMessaging, window.LetAppsAccessMicrophone, window.LetAppsAccessMotion, 
        window.LetAppsAccessNotifications, window.LetAppsAccessPhone, window.LetAppsAccessRadios, 
        window.LetAppsAccessTasks, window.LetAppsAccessTrustedDevices, window.LetAppsActivateWithVoice, 
        window.LetAppsActivateWithVoiceAboveLock, window.LetAppsGetDiagnosticInfo, window.LetAppsRunInBackground, 
        window.LetAppsSyncWithDevices]
    ),
    new category(
        "ASR Rules", 
        "Attack Surface Reduction Rules",
        [window.BADFCCP, window.BAOAFCCP, window.BAOVSD, window.BCSFTWLSAS, window.BECFECAW, 
        window.BEOPOS, window.BJOVFLDEC, window.BOAFCEC, window.BOAFICIOP, 
        window.BOCAFCCP, window.BPCOFPAWC, window.BPTWES, window.BUAUPTRFU, window.BUOCOIST, 
        window.BWACFOM, window.UAPAR]
    ),
    new category(
        "Cloud & Data Synchronization",
        "Endpoints That Control Data Synchronization And Data Sharing Between Devices",
        [window.AllowCrossDeviceClipboard, window.DisableFileSyncNGSC, window.DisableSettingSync, 
        window.EnableCdp, window.MessageCloudSync]
    ),
    new category(
        "Hardware & Sensors",
        "Endpoints That Control Access to Physical Device Hardware",
        [window.AllowCamera, window.AllowFindMyDevice, window.DisableLocation, 
        window.DisableLocationScripting, window.DisableSensors]
    ),
    new category(
        "Privacy & User Experience",
        "Miscellaneous Endpoints That Affect Privacy And System Behavior",
        [window.AllowCloudSearch, window.AllowClipboardHistory, window.AllowCortana, window.AllowInputPersonalization, 
        window.AllowNewsAndInterests, window.DODownloadMode, window.DisableAccountNotifications, window.DisableFileHistory, 
        window.DisableGraphRecentItems, window.DisableSearchBoxSuggestions, 
        window.DisableSoftLanding, window.DisableUAR, window.DisableWindowsSpotlightFeatures, 
        window.EnableActivityFeed, window.MSAOptional, window.TurnOffWindowsCopilot]
    ),
    new category(
        "Remote Desktop",
        "Endpoints That Control Remote Desktop Related Security Settings",
        [window.fDenyTSConnections, window.fDisableAudioCapture, window.fDisableCdm, window.fDisableClip, 
        window.fDisableLocationRedir, window.CSClipLevel, window.SCClipLevel]
    ),
    new category(
        "System Security",
        "Miscellaneous Endpoints That Affect System Security",
        [window.AllowRemoteShellAccess, window.DisablePeerNetworking, window.EnableScriptBlockLogging, window.NeverShowExt, window.NoDriveTypeAutoRun, 
        window.NoRun, window.PreventDeviceMetadataFromNetwork]
    ),
    new category(
        "Telemetry & Data Collection",
        "Endpoints That Control What Data Windows Sends To Microsoft",
        [window.AITEnable, window.AllowDeviceNameInTelemetry, window.AllowLinguisticDataCollection, 
        window.AllowTelemetry, window.CEIPEnable, window.DisableADID, window.DisableAIDataAnalysis, 
        window.DisableApplicationFootprint, window.DisableInstallTracing, window.DisableInventory, 
        window.DisableTailoredExperiencesWithDiagnosticData, window.DisableWindowsConsumerFeatures, 
        window.DisableWindowsErrorReporting, window.PreventNetworkTrafficPreUserSignIn, window.PublishUserActivities, window.ScenarioExecutionEnabled, 
        window.UploadUserActivities]
    ),
    new category(
        "Windows Defender",
        "Core Windows Defender Antivirus And Protection Endpoints",
        [window.DisableAntiSpyware, window.DisableRealTimeMonitoring, window.DisableIOAVProtection, 
        window.DisableBlockAtFirstSeen, window.EnableNetworkProtection, window.MpCloudBlockLevel, 
        window.PUAProtection, window.SpynetReporting, window.SubmitSamplesConsent]
    )
];
